### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by hongkongkiwi** [diazona/pwait#5]
I cannot compile anymore.... there's no such file as sys/capability.h and linux/capability.h doesn't seem to be correct... ?

**Comment by diazona** [comment]
Thanks, I'll look into this. Can you share details of your operating system, including which Linux distribution you run and your kernel version (e.g. output of `uname -rsv`)?

**Comment by diazona** [comment]
Also, I didn't think of it at first, but can you confirm that you have the development package for [libcap](https://sites.google.com/site/fullycapable/) installed? (Which package that is will depend on your distribution.) That's what provides `sys/capability.h`.

**Comment by diazona** [comment]
I'll close this, but I'll be happy to reopen it if I get the information requested.
